services:
    # PostgreSQL database service for Flask
    flask_db_service:
        container_name: flask_db_service
        image: postgres:16
        environment:
            POSTGRES_USER: ${FLASK_DB_USER}
            POSTGRES_PASSWORD: ${FLASK_DB_PASSWORD}
            POSTGRES_DB: ${FLASK_DB_NAME} 
        ports:
            - "5432:5432"  # Map port 5432 on the host to port 5432 in the container
        volumes:
            - postgres_data:/var/lib/postgresql/data  # Persist database data
volumes:
    postgres_data: